trigger:

- main

pool:
  name: default

steps:
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: aspnetcorecontainer
    dockerfile: Dockerfile
    containerRegistry: 'acraz2026'
    tags: latest
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Azure subscription 1(6bde7e67-047b-42c1-9576-47ef47761443)'
    acrName: 'acraz2026'
    imageToDeploy: 'aspnetcorecontainer:latest'
    containerAppName: 'aca-az2006'
    resourceGroup: 'mine'