trigger:

- main

pool:
  name: default

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'myrego'
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: aspnetcorecontainer
    dockerfile: Dockerfile
    containerRegistry: 'myrego'
    tags: latest
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Azure subscription 1(6bde7e67-047b-42c1-9576-47ef47761443)'
    acrName: 'myrego'
    imageToDeploy: 'myrego.azurecr.io/aspnetcorecontainer:latest'
    containerAppName: 'aca-az2006'
    resourceGroup: 'mine'

- task: Docker@2
  inputs:
    containerRegistry: 'myrego'
    repository: 'myapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'