name: Trigger auto deployment for aca-az2006

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-az2006-AutoDeployTrigger-7a9afc29-2164-4627-a000-29985a1c49c2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACAAZ2006_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAAZ2006_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAAZ2006_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acraz2026.azurecr.io
          registryUsername: ${{ secrets.ACAAZ2006_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAAZ2006_REGISTRY_PASSWORD }}
          containerAppName: aca-az2006
          resourceGroup: mine
          imageToBuild: acraz2026.azurecr.io/aca-az2006:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


